blank_issues_enabled: false
contact_links:
  - name: Github wiki
    url: https://github.com/Elikill58/Negativity/wiki
    about: Be sure there isn't answer on the wiki
  - name: Discord quick support
    url: https://discord.gg/KHRVTX2
    about: If you have a quick question, come on discord